### ISSUE TITLE
Canvas interactions sometimes leave behind ghost image remnants

### ISSUE THREAD

**Issue by hbalenda** [digirati-co-uk/canvas-panel#869]
In one of our projects using canvas panel, panning or zooming on a canvas leaves behind image remnants (see screenshot). The remnants disappear on resize, and I wonder if there is an issue with browser performance and repainting the canvas as I have only been able to reproduce the issue in larger projects with many images.

Project repository: https://github.com/thegetty/conserving-canvas
Demo URL (click the first image to open the modal, then pan or zoom): https://www.getty.edu/publications/conserving-canvas/intro/

![Screenshot 2023-08-07 at 3 15 46 PM](https://github.com/digirati-co-uk/canvas-panel/assets/13127674/af95547a-0287-497d-b1e7-396c4db9d6e7)

Please let me know if this rings any bells, any info greatly appreciated!

**Comment by geealbers** [comment]
Turns out that this was being caused by a fix we made for another issue, in which we assigned the a transparent background color to the Atlas element, to override it's otherwise black background color.

```css
:root {
  --atlas-background: transparent;
}
```
We made the background transparent, because there were a few instances in which the background color was showing  through as a thin black line, documented here: https://github.com/thegetty/conserving-canvas/issues/40. However, making `--atlas-background` value anything but transparent, solves this ghosting issue.

**Comment by stephenwf** [comment]
Ah yes, I think that value is used to clear the canvas. It _might_ be possible to use something like: `--atlas-background: rgba(0,0,0,0)` but that might still cause some issues in some browsers, since clearing with a transparent colour doesn't really clear it!
